[package]
name = "chiffre-rsa-enveloppe-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tempfile = "3"

[dependencies.chiffre-rsa-enveloppe]
path = ".."

[dependencies.chiffre-rsa-core]
path = "../../chiffre-rsa-core"

[profile.release]
debug = 1
debug-assertions = true
overflow-checks = true

[[bin]]
name = "decrypt_file_with_key"
path = "fuzz_targets/decrypt_file_with_key.rs"
test = false
doc = false
bench = false

[[bin]]
name = "encrypt_decrypt_roundtrip"
path = "fuzz_targets/encrypt_decrypt_roundtrip.rs"
test = false
doc = false
bench = false
